export {
  hydrate,
  armAutosave,
  cancelPending,
  flushPending,
  getActiveObraId,
  switchObra,
  newObra,
  importObraAsReference,
  deleteObraById,
  discardRecovery,
  descargarCopia,
  importarSobreActiva,
  volverAObraGuardada,
  abrirCambiosAntiguos,
  ignorarCambiosAntiguos,
  aislarPestana,
  descargarCopiaZip,
  restaurarZipSobreActiva,
  __resetSyncForTests,
  type ImportarResult,
  type CopiaZipResult,
  type RestaurarResult,
  type PlanoRestaurado,
  type MotivoNoRestaurado,
} from './sync';
export { useSessionStore, type ReadonlyMotivo } from './sessionStore';
export {
  loadObraEnvelope,
  loadRaw,
  saveObra,
  flush,
  clearObra,
  isObraData,
  obraKey,
  obraKeys,
  versionKey,
  v5ObraKey,
  v5VersionKey,
  V5_OBRA_KEY_PREFIX,
  newerVersionOf,
  OBRA_KEY,
  OBRA_KEY_PREFIX,
  type ObraEnvelope,
  type LoadResult,
  type SaveResult,
} from './persist';
export {
  INDEX_KEY,
  V5_INDEX_KEY,
  listObras,
  loadIndex,
  getActiveId,
  setActiveId,
  createObra,
  deleteObra,
  saveActiveObra,
  reconcile,
  migrateLegacy,
  newObraId,
  loadObraData,
  setUltimaCopia,
  limpiarCopiasV5,
  type MigracionV5,
  type ObraMeta,
  type ObraIndex,
  type LoadObraResult,
  type SaveActiveResult,
} from './registry';
export { usePersistStore, type SaveStatus, type MasNueva } from './persistStore';
export {
  readDurability,
  requestDurability,
  watchDurability,
  type Durability,
} from './durability';
export { PersistUI } from './PersistUI';
export {
  buildExportText,
  exportObraJson,
  parseObraJson,
  readFileText,
  ImportError,
  TOPES_ZIP,
  esCopiaZip,
  leerCopiaZip,
  planCopiaZip,
  descargarPdfsSueltos,
  type ObraExport,
  type ImportErrorKind,
  type CopiaZip,
  type PlanCopiaZip,
} from './transfer';
